class LiteraryGenres {
  static const List<String> genres = [
    "Romance",
    "Fantasia",
    "Ficção Científica",
    "Terror",
    "Suspense / Thriller",
    "Mistério / Policial",
    "Aventura",
    "Drama",
    "Comédia",
    "Poesia",
    "Crônica",
    "Biografia",
    "Autobiografia",
    "Memórias",
    "História",
    "Filosofia",
    "Religião / Espiritualidade",
    "Autoajuda",
    "Negócios / Empreendedorismo",
    "Tecnologia",
    "Ciência",
    "Educação",
    "HQ / Mangá",
    "Infantil",
    "Infantojuvenil",
    "Jovem Adulto",
  ];
}
