// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxixx7HuOio3OxvH8DPVJ50al9RJp7o7A',
    appId: '1:529167144670:web:8a3c80c8319a620e37d44f',
    messagingSenderId: '529167144670',
    projectId: 'me-livrei-app',
    authDomain: 'me-livrei-app.firebaseapp.com',
    storageBucket: 'me-livrei-app.firebasestorage.app',
    measurementId: 'G-D70GY35Y5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNoTOO4IFzio3a5mcl1iTSei3ngFtBXWY',
    appId: '1:529167144670:android:cd86bab5ea53205637d44f',
    messagingSenderId: '529167144670',
    projectId: 'me-livrei-app',
    storageBucket: 'me-livrei-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARt758w1YRMfH1htn8791NfZVIk7ro_gU',
    appId: '1:529167144670:ios:cb008dff609d779e37d44f',
    messagingSenderId: '529167144670',
    projectId: 'me-livrei-app',
    storageBucket: 'me-livrei-app.firebasestorage.app',
    iosBundleId: 'com.example.meLivrei',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARt758w1YRMfH1htn8791NfZVIk7ro_gU',
    appId: '1:529167144670:ios:cb008dff609d779e37d44f',
    messagingSenderId: '529167144670',
    projectId: 'me-livrei-app',
    storageBucket: 'me-livrei-app.firebasestorage.app',
    iosBundleId: 'com.example.meLivrei',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxixx7HuOio3OxvH8DPVJ50al9RJp7o7A',
    appId: '1:529167144670:web:f81d73a0be13d2fb37d44f',
    messagingSenderId: '529167144670',
    projectId: 'me-livrei-app',
    authDomain: 'me-livrei-app.firebaseapp.com',
    storageBucket: 'me-livrei-app.firebasestorage.app',
    measurementId: 'G-89TK9RNE6C',
  );
}
